// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusalaGatewayProject.Context;

namespace MusalaGatewayProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MusalaGatewayProject.Data.Gateway", b =>
                {
                    b.Property<Guid>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Gateways");

                    b.HasData(
                        new
                        {
                            SerialNumber = new Guid("d8835792-079d-4bf6-a92a-4c68d7ffcc3d"),
                            IpAddress = "192.168.1.1",
                            Name = "Gateway-A"
                        },
                        new
                        {
                            SerialNumber = new Guid("028ab19b-ae63-4ec6-ba80-cb2719d3ebd9"),
                            IpAddress = "192.168.2.1",
                            Name = "Gateway-B"
                        },
                        new
                        {
                            SerialNumber = new Guid("35bedc57-cbe4-4d8a-a266-99495a00af5b"),
                            IpAddress = "192.168.3.1",
                            Name = "Gateway-C"
                        });
                });

            modelBuilder.Entity("MusalaGatewayProject.Data.PeripheralDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId");

                    b.ToTable("PeripheralDevices");
                });

            modelBuilder.Entity("MusalaGatewayProject.Data.PeripheralDevice", b =>
                {
                    b.HasOne("MusalaGatewayProject.Data.Gateway", "GatewayNavigation")
                        .WithMany("PeripheralDevices")
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GatewayNavigation");
                });

            modelBuilder.Entity("MusalaGatewayProject.Data.Gateway", b =>
                {
                    b.Navigation("PeripheralDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
